---
title: A simple algorithm to get the TRS-invariant shape different between surgical
  markings
author: "Yunheum Dan Seol"
date: "5/26/2020"
output: pdf_document
---

```{r}
#install all the R packages.
#if the packages are not installed, please uncomment the line below and run it;
#install.packages(c("BiocManager", "magrittr", "shapes", "Rcpp", "RcppArmadillo", "kmlShape"))
#install.packages("vec2dtransf")
#BiocManager::install("EBImage")
```


```{r}
#Import all the required R packages.
library(compiler)
library(magrittr)
library(EBImage)
library(shapes)
library(kmlShape)
library(Rcpp)
library(RcppArmadillo)
library(vec2dtransf)
#these are helper modules written in RcppArmadillo for faster computation
sourceCpp("imageThinning.cpp")
sourceCpp("downSamplePoints.cpp")
```


```{r}
#testing functions in imageThinning.cpp
m1 = matrix(c(1,2,3,4), nrow=2)
m2 = matrix(c(1,2,2,4), nrow=2)
diff = abs_diff(m1, m2)
countNonZero(diff)
```


```{r}
# we read in the images
bilobe1 <- readImage('bilobe1_rgb.png')
bilobe2 <- readImage('bilobe2_rgb.png')
#bilobe1
```

```{r}
#turn images into grayscale
#then turn the surgical marking as white and background as black
binary_bilobe1 <- bilobe1 %>% channel(., "gray") %>% `<`(., 0.5) %>% bwlabel(.)
binary_bilobe2 <- bilobe2 %>% channel(., "gray") %>% `<`(., 0.5) %>% bwlabel(.)

```
```{r}
display(binary_bilobe1)
```

```{r}
display(binary_bilobe2)
```

```{r}
#thin the images
thinned1 <- binary_bilobe1 %>% thinImage
display(thinned1)
```


```{r}
thinned2 <- binary_bilobe2 %>% thinImage
display(thinned2)
```

```{r}
writeImage(thinned1, "thinned_bilobe1.png")
writeImage(thinned2, "thinned_bilobe2.png")
```

```{r}
#print(dim(getCurvePoints(thinned1))) # 1037 2
#print(dim(getCurvePoints(thinned2))) # 1751 2
curvePoints1 <- getCurvePoints(thinned1)
curvePoints2 <- getCurvePoints(thinned2)
dim1 <- dim(curvePoints1)[1]
dim2 <- dim(curvePoints2)[1]
minDim <- min(dim1, dim2)
updatedCurvePoints1 <- DouglasPeuckerNbPoints(curvePoints1$x_coords, curvePoints1$y_coords, minDim)
updatedCurvePoints2 <- DouglasPeuckerNbPoints(curvePoints2$x_coords, curvePoints2$y_coords, minDim)

minDim <- min(dim(updatedCurvePoints1)[1], dim(updatedCurvePoints2)[1])
updatedCurvePoints1 <- DouglasPeuckerNbPoints(curvePoints1$x_coords, curvePoints1$y_coords, minDim)
updatedCurvePoints2 <- DouglasPeuckerNbPoints(curvePoints2$x_coords, curvePoints2$y_coords, minDim)


```


```{r}
learnerMarking <- as.matrix(updatedCurvePoints1) #to feed those in procGPA()
teacherMarking <- as.matrix(updatedCurvePoints2)

```

```{r}
MarkingEvaluation <- setClass(
 # Set the name for the class
 "MarkingEvaluation",
 # Define the slots
 slots = c(
   translation = "matrix",
   rotation  = "numeric",
   scale  = "numeric",
   dissimilarity = "numeric"
 ),
 # Set the default values for the slots. (optional)
 prototype=list(
   rotation = 0,
   scale = 1
 ))
```


```{r}
colMeans(TRSD_raw$Bhat - scale*learnerMarking %*% TRSD_raw$R)
```


```{r}
#we want the learner to do as well as the teacher, not finding a common mean shape
#this means we would need to use OPA, not GPA
procOPAcompiled <- cmpfun(procOPA)
TRSD_raw <- procOPAcompiled(teacherMarking, learnerMarking)
rotationAngleInDegree <- ( TRSD_raw$R[1,1] %>% acos )*180/pi # [[cos theta, sin theta], [-sin theta, cos theta]]
scale <- TRSD_raw$s
translation <- t(as.matrix(colMeans( TRSD_raw$Bhat - scale*learnerMarking %*% TRSD_raw$R)))
colnames(translation) <- c("X", "Y")

TRSD <- MarkingEvaluation(translation = translation,
                  rotation = rotationAngleInDegree,
                  scale = scale,
                  dissimilarity = TRSD_raw$rmsd)

```
```{r}
#In R, there more than two types of custom "containers" - objects.
#there are S3 Objects ("contaiers"), which only contains static data itself.
# you access the data in S3 Objects with dollar sign ($)
#there are also S4 objects, where you can contain both data, and an inner function you can do something with the data it contains
#in that case, you access the components by @
#TRSD
rownames(TRSD@translation) <- c("hello")
```


```{r}
source("getTRSD.R")
```

